service: backend


package:
  include:
    - common/**
  exclude:
    - requirements.txt
    - serverless.yml
    - README.md
    - LICENSE.txt
    
provider:
  name: aws
  runtime: python3.6

functions:
  hello:
    handler: handler.hander
    events:
        - http:
            path: /
            method: post
            cors: true

  getMovies:
    handler: movies/get.get
    events:
        - http:
            path: /getMovies
            method: get
            cors: true
