service: backend

package:
  include:
    - handler.py
  exclude:
    # - requirements.txt
    - serverless.yml
    - README.md
    - LICENSE.txt
    
provider:
  name: aws
  runtime: python3.6

functions:
  recommender:
    handler: handler.hander
    events:
        - http:
            path: /recommender/{id}
            method: get
            cors: true

  getMovies:
    handler: movies/get.get
    events:
        - http:
            path: /getMovies
            method: get
            cors: true
