service: backend


package:
  include:
    - common/**
  exclude:
    - requirements.txt
    - serverless.yml
    - README.md
    - LICENSE.txt
provider:
  name: aws
  runtime: python3.6

functions:
  hello:
    handler: handler.hander
    events:
        - http:
            path: /
            method: post
